apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: laravel
  template:
    apiVersion: v1
    kind: Pod
    metadata:
      name: laravel
      namespace: default
      labels:
        app: laravel
    spec:
      containers:
        -
          name: laravel
          image: laravel
          imagePullPolicy: IfNotPresent
          ports:
            -
              name: http
              protocol: TCP
              containerPort: 80
          env:
            -
              name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: laravel
                  key: DB_HOST
            -
              name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: laravel
                  key: DB_USERNAME
            -
              name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: laravel
                  key: DB_PASSWORD
