{{- if .Values.web.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "larakube.fullname" . }}-cert
  labels:
      {{- include "larakube.labels" . | nindent 4 }}
spec:
  secretName: {{ include "larakube.fullname" . }}-cert-secret
  dnsNames:
    {{- toYaml .Values.web.certManager.domains | nindent 4 }}
  issuerRef:
    name: {{ .Values.web.certManager.issuer }}
    kind: ClusterIssuer
{{- end }}
