{{- if .Values.web.traefik.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "larakube.fullname" . }}-traefik-ingress
  labels:
    {{- include "larakube.labels" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.web.traefik.domain }}`)
      kind: Rule
      services:
        - name: {{ include "larakube.fullname" . }}-web
          port: {{ .Values.service.port }}
      middlewares:
        {{- if or .Values.web.traefik.customRequestHeaders .Values.web.traefik.customResponseHeaders }}
        - name: {{ include "larakube.fullname" . }}-traefik-middleware-custom-headers
        {{- end }}
        {{- if .Values.web.traefik.compress }}
        - name: {{ include "larakube.fullname" . }}-traefik-middleware-compress
        {{- end }}
        {{- if .Values.web.traefik.basicAuth.enabled }}
        - name: {{ include "larakube.fullname" . }}-traefik-middleware-basic-auth
        {{- end }}
        {{- range $key, $value := .Values.web.traefik.extraMiddlewares }}
        - name: {{ $value }}
        {{- end }}
  tls:
    secretName: {{ include "larakube.fullname" . }}-cert-secret
---
{{- if and .Values.web.traefik.basicAuth.enabled .Values.web.traefik.basicAuth.allowBypassForIpRanges -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "larakube.fullname" . }}-traefik-ingress-bypass-basic-auth
  labels:
    {{- include "larakube.labels" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.web.traefik.domain }}`) && ClientIP(`{{ join "`, `" .Values.web.traefik.basicAuth.allowBypassForIpRanges }}`)
      kind: Rule
      services:
        - name: {{ include "larakube.fullname" . }}-web
          port: {{ .Values.service.port }}
      middlewares:
        {{- if or .Values.web.traefik.customRequestHeaders .Values.web.traefik.customResponseHeaders }}
        - name: {{ include "larakube.fullname" . }}-traefik-middleware-custom-headers
        {{- end }}
        {{- if .Values.web.traefik.compress }}
        - name: {{ include "larakube.fullname" . }}-traefik-middleware-compress
        {{- end }}
        {{- range $key, $value := .Values.web.traefik.extraMiddlewares }}
        - name: {{ $value }}
        {{- end }}
  tls:
    secretName: {{ include "larakube.fullname" . }}-cert-secret
---
{{- end -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "larakube.fullname" . }}-traefik-ingress-redirect-to-https
  labels:
    {{- include "larakube.labels" . | nindent 4 }}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ .Values.web.traefik.domain }}`)
      kind: Rule
      services:
        - name: noop@internal
          kind: TraefikService
      middlewares:
        - name: {{ include "larakube.fullname" . }}-traefik-middleware-permanent-redirect-https
---
{{- range $i, $value := .Values.web.traefik.domainRedirects }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "larakube.fullname" $ }}-traefik-ingress-https-domain-redirect-{{ $value.domain | replace "." "-" | kebabcase }}
  labels:
    {{- include "larakube.labels" $ | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ $value.domain }}`)
      kind: Rule
      services:
        - name: noop@internal
          kind: TraefikService
      middlewares:
        - name: {{ include "larakube.fullname" $ }}-traefik-middleware-domain-redirect-{{ $value.domain | replace "." "-" | kebabcase }}
  tls:
    secretName: {{ include "larakube.fullname" $ }}-cert-secret
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "larakube.fullname" $ }}-traefik-ingress-http-domain-redirect-{{ $value.domain | replace "." "-" | kebabcase }}
  labels:
    {{- include "larakube.labels" $ | nindent 4 }}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ $value.domain }}`)
      kind: Rule
      services:
        - name: noop@internal
          kind: TraefikService
      middlewares:
        - name: {{ include "larakube.fullname" $ }}-traefik-middleware-domain-redirect-{{ $value.domain | replace "." "-" | kebabcase }}
---
{{- end }}
{{- end }}
