{{- if .Values.databaseMigration.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "larakube.fullname" . }}-db-migrate
  labels:
    {{- include "larakube.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: {{ .Values.databaseMigration.retry }}
  template:
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "larakube.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - ls -al && pwd && php artisan migrate --isolated --force
          env:
            # TODO: check if there are any envs
            {{- range $key, $value := .Values.databaseMigration.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range $key, $value := .Values.secretEnvs }}
              {{- if $value.existing }}
            - name: {{ $value.name }}
              valueFrom:
                secretKeyRef:
                  name: {{ $value.secretName }}
                  key: {{ $value.secretKey }}
              {{- end }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "larakube.fullname" . }}-env
          resources:
            {{- toYaml .Values.databaseMigration.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}
