{{- if .Values.web.traefik.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "larakube.fullname" . }}-traefik-middleware-compress
  labels:
    {{- include "larakube.labels" . | nindent 4 }}
spec:
  compress:
    minResponseBodyBytes: 1200
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "larakube.fullname" . }}-traefik-middleware-custom-headers
  labels:
    {{- include "larakube.labels" . | nindent 4 }}
spec:
  headers:
    {{- with .Values.web.traefik.customRequestHeaders }}
    customRequestHeaders:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.web.traefik.customResponseHeaders }}
    customResponseHeaders:
      {{- toYaml . | nindent 6 }}
    {{- end }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "larakube.fullname" . }}-traefik-middleware-permanent-redirect-https
  labels:
    {{- include "larakube.labels" . | nindent 4 }}
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
{{- end }}
