apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: default
spec:
  type: NodePort
  ports:
    -
      name: http
      port: 3306
      targetPort: 3306
  selector:
    app: database
