{{ if .Values.scheduler.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "larakube.fullname" . }}-scheduler
  labels:
    {{- include "larakube.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.scheduler.schedule | quote }}
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "larakube.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
            - name: {{ .Chart.Name }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command:
                - /bin/sh
                - -c
                - php artisan schedule:run
              env:
                # TODO: check if there are any envs
                {{- range $key, $value := .Values.web.env }}
                - name: {{ $key }}
                  value: {{ $value | quote }}
                {{- end }}
                {{- range $key, $value := .Values.secretEnvs }}
                {{- if $value.existing }}
                - name: {{ $value.name }}
                  valueFrom:
                    secretKeyRef:
                      name: {{ $value.secretName }}
                      key: {{ $value.secretKey }}
                {{- end }}
                {{- end }}
              envFrom:
                - configMapRef:
                    name: {{ include "larakube.fullname" . }}-env
              resources:
                {{- toYaml .Values.scheduler.resources | nindent 16 }}
              {{- with .Values.volumeMounts }}
              volumeMounts:
                {{- toYaml . | nindent 16 }}
              {{- end }}
          restartPolicy: OnFailure
          {{- with .Values.volumes }}
          volumes:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
