{{- range $i, $value := .Values.worker }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "larakube.fullname" $ }}-worker-{{ $i }}
  labels:
    {{- include "larakube.labels" $ | nindent 4 }}
spec:
  {{- if not $value.autoscaling.enabled }}
  replicas: {{ $value.replicaCount }}
  {{- end }}
  strategy: # TODO: add support for custom strategy
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  revisionHistoryLimit: {{ $.Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "larakube.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: worker-{{ $i }}
  template:
    metadata:
      {{- with $value.podAnnotations }}
      annotations:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
      labels:
        {{- include "larakube.labels" $ | nindent 8 }}
        app.kubernetes.io/component: worker-{{ $i }}
        {{- with $.Values.podLabels }}
        {{- toYaml $ | nindent 8 }}
        {{- end }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "larakube.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $.Chart.Name }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          env:
            # TODO: check if there are any envs
            {{- range $key, $value := $value.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range $key, $value := $.Values.secretEnvs }}
            {{- if $value.existing }}
            - name: {{ $value.name }}
              valueFrom:
                secretKeyRef:
                  name: {{ $value.secretName }}
                  key: {{ $value.secretKey }}
            {{- end }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "larakube.fullname" $ }}-env
          #livenessProbe: TODO
          #  { {- toYaml $value.livenessProbe | nindent 12 }}
          #readinessProbe:
          #  { {- toYaml $value.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml $value.resources | nindent 12 }}
          {{- with $.Values.volumeMounts }}
          volumeMounts:
            {{- toYaml $ | nindent 12 }}
          {{- end }}
      {{- with $.Values.volumes }}
      volumes:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
{{- end }}
