on:
  push:
    branches:
      - main
  workflow_dispatch:

name: Deploy
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out code"
        uses: actions/checkout@v4

      - name: "Go to docs folder"
        run: cd docs

      - name: "Install dependencies"
        run: npm ci

      - name: "Build"
        run: npm run build

      - name: "Upload artifact"
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: build
          compression-level: 9
          if-no-files-found: error

      - name: "Setup PHP with PECL extension"
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, bcmath, soap, intl, gd, exif

      - name: "Download Fastfront CLI"
        run: curl https://fastfront-cli.s3.fr-par.scw.cloud/fastfront-cli.phar -o fastfront-cli.phar

      - name: "Deploy with Fastfront"
        run: php fastfront-cli.phar deploy $FASTFRONT_STAGE ./dist
        env:
          FASTFRONT_STAGE: ${{ '9d7ef70e-f7d1-4c7e-aeb5-b066fc54eb32' }}
          FASTFRONT_API_KEY: ${{ secrets.FASTFRONT_CHART_API_KEY }}
