name: Lint Helm Chart

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Install Helm"
        uses: azure/setup-helm@v4

      - name: "Lint helm chart"
        run: helm lint charts/larakube --values charts/larakube/values.yaml

      - name: "Build helm chart"
        run: helm template charts/larakube --values charts/larakube/values.yaml --output-dir build --debug

      - name: "Upload artifact"
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build
          compression-level: 9
          if-no-files-found: error
