name: Release Helm Chart

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Configure Git"
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: "Install Helm"
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Copy readme"
        run: cp readme.md charts/larakube/README.md

      - name: "Run chart-releaser"
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Run GitHub action workflow manually"
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: larakube
          repo: larakube
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          workflow_file_name: deploy-chart.yml
          ref: gh-pages
